#base_frame: "/base_laser_front_link"
base_frame: "/robot_0/odom"
transform_wait_timeout: 0.5
segmentation:
    type: "AdaptiveThresholdDetection"
    angle: 0.2
    sigma: 0.2
filtering:
  points_number:
    min_points: 5
    max_points: 100
  area:
    min_area: 0.005
    max_area: 1.0
    min_dimension: 0.05
  occlusion:
    max_angle_gap: 0.09 # 5 degrees
feature_extraction:
  occlusion_checking:
    distance_threshold: 0.1
  min_angle_between_lines: 0.2
  max_distance: 0.05
  rho_resolution: 0.05
  theta_resolution: 0.04
  voting_threshold: 10
tracking:
  object_matching:
    buffer_length: 2.0
    min_buffer_filling: 1.0
    distance_threshold: 0.1
    orientation_angle_threshold: 0.17 # 10 degrees
    aperture_angle_threshold: 0.17 # 10 degrees
  model:
    time_step: 0.1
    max_mahalanobis_distance: 0.5
    skip_decay_rate: 20.0
    probability_start: 0.01
    probability_detection: 0.9
    measurement_noise_covariance: [0.1, 0.0,
                                   0.0, 0.1]
    initial_state_covariance: [0.1, 0.0, 0.0, 0.0,
                               0.0, 0.1, 0.0, 0.0,
                               0.0, 0.0, 0.1, 0.0,
                               0.0, 0.0, 0.0, 0.1]
    process_noise_covariance: [0.2, 0.0, 0.0, 0.0,
                               0.0, 0.2, 0.0, 0.0,
                               0.0, 0.0, 0.2, 0.0,
                               0.0, 0.0, 0.0, 0.2]
  false_alarm_likelihood: 0.1
  max_depth: 1
  min_g_hypothesis_ratio: 0.001
  max_g_hypothesis: 100